import { describe, expect, it } from "vitest";
import { emptyGuestProgress, guestOverview, guestProgressSchema, guestDraftKey, type GuestLearningCatalog } from "./local-progress";
const ids = ["00000000-0000-4000-8000-000000000001", "00000000-0000-4000-8000-000000000002", "00000000-0000-4000-8000-000000000003", "00000000-0000-4000-8000-000000000004", "00000000-0000-4000-8000-000000000005"];
const catalog: GuestLearningCatalog = { path: { id: ids[0]!, slug: "database-fundamentals", title: "Basis Data", description: "Belajar" }, lessons: ids.slice(0, 2).map((id, i) => ({ id, chapter_id: ids[0]!, slug: `materi-${i}`, title: `Materi ${i}`, summary: "Konsep", position: i + 1, is_required: true, is_preview: false, chapterPosition: 1, chapterTitle: "Relasi", chapterIsRequired: true })), exercises: [{ id: ids[2]!, lesson_id: ids[0]! }, { id: ids[3]!, lesson_id: ids[1]! }], tests: [{ id: ids[4]!, title: "Pre-test", type: "PRETEST", passing_score: 0 }] };
const baseline = { ...emptyGuestProgress, tests: { [ids[4]!]: { score: 0, passed: false, totalCorrect: 0, totalItems: 10 } } };
describe("local guest progression", () => {
 it("opens the first material without a diagnostic or saved progress", () => { const view = guestOverview(catalog, emptyGuestProgress)!; expect(view.baselineComplete).toBe(true); expect(view.metrics.percentage).toBe(0); expect(view.lessons.map(lesson => lesson.state)).toEqual(["AVAILABLE", "LOCKED"]); });
 it("any completed diagnostic unlocks the first material", () => { const view = guestOverview(catalog, baseline)!; expect(view.lessons.map((lesson) => lesson.state)).toEqual(["AVAILABLE", "LOCKED"]); });
 it("reading alone does not complete a material", () => { const view = guestOverview(catalog, { ...baseline, read: { [ids[0]!]: "2026-10-07T00:00:00.000Z" } })!; expect(view.lessons[0]?.state).toBe("IN_PROGRESS"); expect(view.lessons[1]?.state).toBe("LOCKED"); });
 it("a pass alone does not bypass reading", () => { expect(guestOverview(catalog, { ...baseline, passedExercises: [ids[2]!] })!.metrics.percentage).toBe(0); });
 it("reading and every required exercise unlock next material", () => { const view = guestOverview(catalog, { ...baseline, read: { [ids[0]!]: "2026-10-07T00:00:00.000Z" }, passedExercises: [ids[2]!] })!; expect(view.metrics.percentage).toBe(50); expect(view.lessons.map((lesson) => lesson.state)).toEqual(["COMPLETED", "AVAILABLE"]); expect(view.metrics.currentLesson?.id).toBe(ids[1]); });
 it("does not complete a lesson with no core published", () => { expect(guestOverview({ ...catalog, exercises: [] }, { ...baseline, read: { [ids[0]!]: "2026-10-07T00:00:00.000Z" } })!.metrics.percentage).toBe(0); });
 it("reaches 100% from local required completions", () => { const view = guestOverview(catalog, { ...baseline, read: Object.fromEntries(ids.slice(0, 2).map((id) => [id, "2026-10-07T00:00:00.000Z"])), passedExercises: ids.slice(2, 4) })!; expect(view.metrics.percentage).toBe(100); expect(view.metrics.currentLesson).toBeNull(); });
 it("restores across new signed guest IDs while keeping exercise IDs distinct", () => { expect(guestDraftKey(`practice:${ids[0]}:${ids[2]}`)).toBe(guestDraftKey(`practice:${ids[1]}:${ids[2]}`)); expect(guestDraftKey(`practice:${ids[0]}:${ids[2]}`)).not.toBe(guestDraftKey(`practice:${ids[0]}:${ids[3]}`)); });
 it("rejects malformed saved progress and strips unsupported fields", () => { expect(guestProgressSchema.safeParse({ ...baseline, passedExercises: ["invalid"] }).success).toBe(false); expect(guestProgressSchema.parse({ ...baseline, role: "ADMIN" })).not.toHaveProperty("role"); });
});
