import { Database, KeyRound, ArrowDown } from "lucide-react";

export function DatabaseLabPreview() {
  return <figure className="min-w-0 rounded-lg border border-border bg-white" aria-labelledby="lab-preview-title">
    <div className="flex items-center justify-between gap-3 border-b border-border px-5 py-4"><h2 id="lab-preview-title" className="flex items-center gap-2 text-sm font-semibold"><Database size={17} className="text-primary" aria-hidden="true" />Lab basis data</h2><span className="text-xs text-muted-foreground">Contoh visual</span></div>
    <div className="p-5 sm:p-6"><div className="grid min-w-0 grid-cols-1 items-center gap-2 min-[480px]:grid-cols-[minmax(0,1fr)_1.25rem_minmax(0,1fr)]" aria-label="Relasi satu mahasiswa ke banyak pendaftaran">
      <div className="min-w-0 rounded-md border border-border"><h3 className="rounded-t-md bg-secondary px-3 py-2 font-mono text-xs font-semibold">students</h3><p className="flex flex-wrap items-center gap-1.5 px-3 py-2 font-mono text-xs"><KeyRound size={12} className="shrink-0" aria-label="Primary key" />student_id</p><p className="border-t border-border px-3 py-2 font-mono text-xs">name</p><p className="border-t border-border px-3 py-2 font-mono text-xs">cohort</p></div>
      <span aria-hidden="true" className="mx-auto h-5 w-px bg-primary min-[480px]:h-px min-[480px]:w-full" />
      <div className="min-w-0 rounded-md border border-border"><h3 className="rounded-t-md bg-live-surface px-3 py-2 font-mono text-xs font-semibold">enrollments</h3><p className="px-3 py-2 font-mono text-xs">student_id · FK</p><p className="border-t border-border px-3 py-2 font-mono text-xs">course_id · FK</p></div>
    </div><p className="mt-3 text-xs leading-5 text-muted-foreground">Satu mahasiswa, beberapa pendaftaran.</p><div className="mt-5 border-t border-border pt-4"><p className="text-sm font-medium">Siapa mahasiswa angkatan 2024?</p><pre className="mt-3 overflow-x-auto rounded-md bg-muted p-3 font-mono text-xs leading-6"><code><span className="text-primary">SELECT</span> name <span className="text-primary">FROM</span> students{"\n"}<span className="text-primary">WHERE</span> cohort = &apos;2024&apos;;</code></pre><ArrowDown size={17} className="mx-auto my-3 text-muted-foreground" aria-hidden="true" /><div className="flex items-center justify-between rounded-md bg-live-surface px-3 py-3 text-sm"><span>Citra · Danu</span><span className="text-xs text-muted-foreground">2 record</span></div></div></div>
  </figure>;
}
